remove checknecprog()

diff --git a/gitsethook b/gitsethook
--- a/gitsethook
+++ b/gitsethook
@@ -1,20 +1,17 @@
 #!/bin/bash
 
+PN="${BASH_SOURCE[0]##*/}"
+PD="${BASH_SOURCE[0]%/*}"
+
+source "${PD}/lib/die"
+
 function usage() {
 	cat <<EOF
-Usage: ${0} <Project>
+Usage: ${PN} <Project>
+Options:
+  -h       : show this help message
 EOF
-	if [ $# -gt 0 ] ; then
-		echo "$@" >&2
-		exit 1
-	else
-		exit
-	fi
-}
-
-function die() {
-	echo "$@" >&2
-	exit 1
+	[ $# -gt 0 ] && { echo ; die "$@" ; } || exit 0
 }
 
 # $1: command
@@ -43,6 +40,20 @@ function sethook() {
 	addCmdToFile "exec git update-server-info" "post-receive"
 	popd &>/dev/null
 }
+
+type getopt cat grep chmod git >/dev/null || exit $?
+
+(($# == 0)) && usage "Invalid parameters"
+opt="$(getopt -o h -- "$@")" || usage "Parse options failed"
+
+eval set -- "${opt}"
+while true ; do
+	case "${1}" in
+	-h) usage ; shift ;;
+	--) shift ; break ;;
+	*) echo "Internal error!" ; exit 1 ;;
+	esac
+done
 
 for i in "$@" ; do
 	sethook "${i}"
diff --git a/tbz b/tbz
--- a/tbz
+++ b/tbz
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-PN="$(basename "${0}")"
+PN="${BASH_SOURCE[0]##*/}"
+PD="${BASH_SOURCE[0]%/*}"
+
+source "${PD}/lib/die"
 
 function usage() {
 	cat <<EOF
@@ -15,34 +18,28 @@ EOF
 	[ $# -gt 0 ] && { echo ; die "$@" ; } || exit 0
 }
 
-function die() {
-	echo "$@" >&2
-	exit 1
-}
+case "${PN}" in
+t7z) type 7z >/dev/null || exit $? ;;
+*) type tar >/dev/null || exit $? ;;
+esac
 
-opt="$(getopt -o hD: -- "$@")"
-(($? != 0)) && usage
+opt="$(getopt -o hD: -- "$@")" || usage "Parse options failed"
+
 eval set -- "${opt}"
 while true ; do
 	case "${1}" in
 	-h) usage ;;
-	-D) tdir="${2%/}" ; shift 2 ;;
+	-D) tdir="${2%%/}" ; shift 2 ;;
 	--) shift ; break ;;
 	*) die "Internal error!" ;;
 	esac
 done
 
-if [ "${1}" ] ; then
-	src="${1}"
-else
-	src="."
-fi
-
-src="$(readlink -f "${src}")"
+src="$(readlink -f "${1:-.}")"
 [ "${src}" == "/" ] && die "Input path cannot be '/'"
 
-d="$(dirname "${src}")"
-src="$(basename "${src}")"
+d="${src%/*}"
+src="${src##*/}"
 
 if [ "${PN}" == "t7z" ] ; then
 	tar="${src}.7z"
@@ -58,12 +55,9 @@ fi
 
 pushd "${d}" &>/dev/null
 
-if [ ! -e "${src}" ] ; then
-	echo "'${src}' not found" >&2
-	exit 1
-fi
+[ -e "${src}" ] || die "'${src}' not found"
 
-pwd
+echo "${PWD}"
 if [ "${PN}" == "t7z" ] ; then
 	7z a -m0=lzma -mx=9 -mfb=273 -md=32m "${tar}" "${src}"
 else
